const TT = {
  API: {
    ORGS:  "https://claude.ai/api/organizations",
    USAGE: (id) => `https://claude.ai/api/organizations/${id}/usage`,
  },
  LIMITS: {
    "default":         200000,
    "claude-sonnet-4": 200000,
    "claude-opus-4":   200000,
    "claude-haiku-4":  200000,
    "gpt-4o":          128000,
    "gpt-4":           128000,
    "gpt-3.5":         16385,
    "o1":              200000,
    "o3":              200000,
  },
  WARN:   70,
  DANGER: 90,
  COLOR: {
    GREEN:  "#22c55e",
    YELLOW: "#f59e0b",
    RED:    "#ef4444",
  },
  KEY: {
    ORG_ID:   "tt_org_id",
    USAGE:    "tt_claude_usage",
    CONTEXT:  "tt_context",
    HISTORY:  "tt_history",
    SETTINGS: "tt_settings",
    NOTIFIED: "tt_last_notified",
  },
  ALARM: "tt_fetch",
  DEFAULTS: {
    notify_50:       false,
    notify_75:       true,
    notify_90:       true,
    notify_100:      true,
    refresh_minutes: 5,
    show_bar:        true,
  },
};